/*
 * p.web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ItemApiCli.Client;
using ItemApiCli.Api;
// uncomment below to import models
//using ItemApiCli.Model;

namespace ItemApiCli.Test.Api
{
    /// <summary>
    ///  Class for testing ItemsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ItemsApiTests : IDisposable
    {
        private ItemsApi instance;

        public ItemsApiTests()
        {
            instance = new ItemsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ItemsApi
            //Assert.IsType<ItemsApi>(instance);
        }

        /// <summary>
        /// Test ItemsAddItemPost
        /// </summary>
        [Fact]
        public void ItemsAddItemPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ToDoItems toDoItems = null;
            //instance.ItemsAddItemPost(toDoItems);
        }

        /// <summary>
        /// Test ItemsDeleteitemIdiDelete
        /// </summary>
        [Fact]
        public void ItemsDeleteitemIdiDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string idi = null;
            //instance.ItemsDeleteitemIdiDelete(idi);
        }

        /// <summary>
        /// Test ItemsGet
        /// </summary>
        [Fact]
        public void ItemsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ItemsGet();
            //Assert.IsType<List<ToDoItems>>(response);
        }

        /// <summary>
        /// Test ItemsGetItemIdGet
        /// </summary>
        [Fact]
        public void ItemsGetItemIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ItemsGetItemIdGet(id);
            //Assert.IsType<ToDoItems>(response);
        }
    }
}
